### ISSUE TITLE
Incoherent handling of links between preview and real rendering mode.

### ISSUE THREAD

**Issue by mkende** [Requarks/wiki#1076]
**Describe the bug**
If the home page of a wiki (`example.com/` or `example.com/fr/home`) contains the following link: `[test](dir/foo.md)` then in preview mode the target of the link is correctly the `example.com/fr/dir/foo.md` page. But once rendered, the link points to `example.com/fr/home/dir/foo.md` (notice the `home` dir in the path).

**To Reproduce**
1. Edit the home page of a wiki
2. Add a relative link
3. click on the link in the preview pane
4. submit the page and click on the link in the rendered page.

**Expected behavior**
Both links points to the same page, probably the one without the `home` directory in its path.

**Host Info (please complete the following information):**
 - OS: Debian stable
 - Wiki.js version: e.g. 2.0.0-beta.303
 - Database engine: sqlite

**Comment by mkende** [comment]
Just a note that issue #1169 seems to be a duplicate of this one (which is indeed still present for me in rc-17). It is a regression between beta-275 and beta-303 that entirely breaks navigating inside the wiki except through the side menu.
Let me know if there is something that I can do to help you diagnose this issue.

**Comment by NGPixel** [comment]
Fixed by 8ba78dd771b5707b380f686bb8382140e1976970

**Comment by S1M0N** [comment]
Just updated to `2.0.1` as it shows in the change log that this fix was implemented in that release (https://github.com/Requarks/wiki/commit/8ba78dd771b5707b380f686bb8382140e1976970), unfortunately it seems that this same issue is still appearing in `2.0.1`.

**Comment by mkende** [comment]
I can confirm that this is still happening. Can the bug be marked as re-opened?

**Comment by mkende** [comment]
Actually, I think that this *is* fixed but, after the update, the home page needs to be re-rendered so that the links are fixed (sounds obvious once you say it...).
