### ISSUE TITLE
Group Permissions & Page Rules not working in v2.0.1

### ISSUE THREAD

**Issue by ravenzachary** [Requarks/wiki#1228]
**Describe the bug**
After creating a new Group called Authors, a User with this Group is not allowed to edit a page. An unauthorized page is displayed upon editing. The setting are as follows (also, see screenshots):

Permissions: 
read:pages
write:pages
read:source
read:history
read:assets
write:assets
read:comments
write:comments

Page Rules:
Read Pages
Create Pages
Edit + Move Pages
View Page Source
View Pages History
Read / Use Assets
Upload Assets
Read Comments
Create Comments

Path Starts With:
Any Locale
/

**To Reproduce**
1. Login as a user with with the Authors group.
2. Attempt to edit a page. Wiki.js displays an "Unauthorized" page.

**Expected behavior**
Any user in the Authors groups should be allowed to edit a page.

**Screenshots**
![Screen Shot 2019-11-18 at 3 17 26 PM](https://user-images.githubusercontent.com/645975/69102370-17eaa280-0a17-11ea-927f-02d192af7228.png)
![Screen Shot 2019-11-18 at 3 17 39 PM](https://user-images.githubusercontent.com/645975/69102372-1a4cfc80-0a17-11ea-8630-c69398885057.png)
![Screen Shot 2019-11-18 at 3 17 45 PM](https://user-images.githubusercontent.com/645975/69102376-1caf5680-0a17-11ea-944c-05352525e093.png)
![Screen Shot 2019-11-18 at 3 18 05 PM](https://user-images.githubusercontent.com/645975/69102380-2042dd80-0a17-11ea-838d-ab7a50dec429.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 190.04 x64
 - Wiki.js version: 2.0.1
 - Database engine: postgres

**Additional context**

**Comment by ravenzachary** [comment]
I also tried adding a specific path in Page Rules in to see if that was required, and it had the same Unauthorized page results.

**Comment by pirvana** [comment]
Good, I also have the same problems, would there be any solution for this?

**Comment by pirvana** [comment]
@ravenzachary :  You must create a rule where the user can access the home

![image](https://user-images.githubusercontent.com/23135703/69375969-34d9dc80-0c88-11ea-81ba-00ab3a724894.png)

**Comment by ravenzachary** [comment]
Thank you for adding your comments to this ticket. but unfortunately that did not fix the problems for me. I still see an Unauthorized warning page for any page I try to edit.

**Comment by pirvana** [comment]
Good, conducting tests, also to me, the same error appeared to me, my solution was, what I had already told you, and apart create a group (deny) where I removed access to pages that I do not want the other users to enter, I hope this helps to solve or palliate the problem

**Comment by NGPixel** [comment]
Fixed by 49819b41db42be41cf246fafe7b1612a11bd2fac

**Comment by VilterPD** [comment]
I'm sorry, it isn't solved I'm having the exact same problem in 2024 with 2.5.303

**Comment by rkonnad** [comment]
I'm also having the same issue with 2.5.303.

In my case, I have a group set up with basically full access and then a page rule with the same access granted for a URL that starts with /information-technology. I can view, create, edit, delete, etc. pages directly under /information-technology but as soon as I try to create a page any further down that that top level, for instance /information-technology/internal/new-page, I can create it, and I can edit it, but I am greeted with the "Unauthorized" error page. Oddly, I can get back to edit mode by creating a "new" page at the same URL.

**Comment by VilterPD** [comment]
I set up a page rule for all access to everything that starts with /, which works. Not ideal though.

**Comment by vnpenguin** [comment]
I have the same issue with 2.5.306:  Pages rules is defined for some group with some path, but users can not edit the page.
Any help?

**Comment by hkazaz** [comment]
I have the same issue with 2.5.306  , 
At permissions tab user of group has ""all" of the  "Content"  permissions whithout any exception ,
At page-rules, all rights given for "Path Start With"  root path ('/') 
tested immediately after logout-login , 
there is no restrictedAccess in any configuration file

**Comment by hkazaz** [comment]
In "static async deletePage(opts)"  in  "https://github.com/requarks/wiki/blob/main/server/models/pages.js"  file 
should  the line "locale: page.locale"  below be "locale: page.localeCode" ?? 

static async deletePage(opts) {
    ... 
    // -> Check for page access
    if (!WIKI.auth.checkAccess(opts.user, ['delete:pages'], {
      locale: page.locale,
      path: page.path
    }))

**Comment by BorisMolch** [comment]
im having the same issue with latest release 2.5.307

**Comment by BorisMolch** [comment]
> im having the same issue with latest release 2.5.307

resolved
i had an issue with my token
