### ISSUE TITLE
telephone links

### ISSUE THREAD

**Issue by vladisalv** [Requarks/wiki#1318]
When I try to create a telephone link (tel:DIGITS), wiki interpreters  it like a usual link: example.com/page/tel:DIGITS

**Expected behavior**
Call a system app like it does for mail links (mailto:example@site.com - works fine!)

**Host Info:**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: [e.g. 2.0.12]

**Comment by ssimontis** [comment]
@vladisalv I believe I have fixed the issue, would you be willing to test against the main branch and verify? Thanks!

**Comment by NGPixel** [comment]
Fixed by bb03aed1c8741ba1be1d524ba300e17862a0ad56

**Comment by vladisalv** [comment]
Hi guys! Sorry for missing, didn't have a time to update wiki.js
I'm using **Wiki.js 2.1.113** and still have this error.
My contact page has the following markdown snippet:
`mail [example@example.com](mailto:example@example.com)
*telephone [+7 XXX XXX XX XX](tel:+7XXXXXXXXXX)`
it opens mail client if i click the first link (as I suppose) and open page with url  https://wiki.oitheatre.ru/ru/contacts/tel:+79168089244 in browser if I click tel link. I suppose to open tel link in my call app on smartphone, but it's not.

**Comment by justinacolmena** [comment]
Now I seem to recall, the "+" sign is an invalid character within a "tel:" url. Try

[+7 XXX XXX XX XX](tel:7XXXXXXXXXX)

without the plus sign. The hyphen or minus "-" would okay, but that is not the custom outside North America.

On March 14, 2020 4:04:37 PM AKDT, Vladislav Toigildin <notifications@github.com> wrote:
>Hi guys! Sorry for missing, didn't have a time to update wiki.js
>I'm using **Wiki.js 2.1.113** and still have this error.
>My contact page has the following markdown snippet:
>`mail [example@example.com](mailto:example@example.com)
>*telephone [+7 XXX XXX XX XX](tel:+7XXXXXXXXXX)`
>it opens mail client if i click the first link (as I suppose) and open
>page with url  https://wiki.oitheatre.ru/ru/contacts/tel:+79168089244
>in browser if I click tel link. I suppose to open tel link in my call
>app on smartphone, but it's not.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Requarks/wiki/issues/1318#issuecomment-599149932

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
