### ISSUE TITLE
[New feature] Allow internal link by page ID

### ISSUE THREAD

**Issue by Yivan** [Requarks/wiki#1369]
Hello,

Linking page in any wiki can lead to tiedous task if hard path is used and the targeting page gets its path changed. It involves knowing all pages were this page is called and change on each page the path.

Actually there is no tools to detect global dead internal link (a summary of all page having dead links), so we cannot correct them after renaming a page. The pageLinks table in database cannot be of great help because it don't have the source page information.
Parsing with LIKE request the page table can be a way... but very technical.

**Proposition of redirection:**
One way, the easiest one, would be to allow direct access page by ID.
So we can use internal link with a markdown like `pageid/9`. This will give:

```
[My Link To Page ID 9](pageid/9)
```
It will be just a redirection a the path of page id 9. So no permissions to check as it will be handled on the redirection target page which will be the full path as usual.
`https://mydomain.com/pageid/9` redirect to `https://mydomain.com/en/the/full/path`

So this is just a redirection to put in place.
(another way, could be to retrieve the path of the page id during rendering, but this will be as a little more code than just put redirection in place, but will be more proper)
It will really make life easier on big wiki using internal linking! Really.
Changing path is a lot more frequent than deleting a page/changing it's id, so I think it is valuable.

**Proposition of global dead link detector:** (later, redirection will mitigate its need)
In parrallel of the redirection feature, but can be done in a second time, in the adminsitration area in the page tools, a global internal dead link will be really really welcome. So we can easily check all internal linking is OK, and know whcih page we must change after deleting a page for instance.

I hope all of this make sense.
Actually we are using internal link and changing path (for better structure) is always a risky task as we can easily miss the page using the old links.

I know there is a dead link detection in place (which display the link in red), but it is not very helful if we need to go manually on each pages. I think it is just to show to the end-user that the link don't work and it is its work to report it... Here purpose of this issue is to be proactive and having the tools to make proper internal linking.

Thanks a lot, ... and i forgot your wiki is awesome ; )

**Comment by NGPixel** [comment]
Please use the [feature request board](https://wiki.js.org/feedback), Github is for bugs/help only.

A similar request already exists at https://wiki.js.org/feedback/p/page-ids-for-indexing and it's actually coming in 2.1

**Comment by Yivan** [comment]
Thanks @NGPixel I posted this issue on the Canny support area.

I really hope at least a simple HTTP redirection header could be implemented (from pageid/9 to /ful/path/to/the/page).

**Comment by Yivan** [comment]
For those following this issue, it has been resolved in 2.1 (completed: https://wiki.js.org/feedback/p/page-ids-for-indexing).
Thanks

**Comment by suwubee** [comment]
> Please use the [feature request board](https://wiki.js.org/feedback), Github is for bugs/help only.
> 
> A similar request already exists at https://wiki.js.org/feedback/p/page-ids-for-indexing and it's actually coming in 2.1

still not find where to modify.

**Comment by lovelock** [comment]
I can't find out where to get the page id if I am not the administrator, so editors still can't share urls with the page id ones

**Comment by NGPixel** [comment]
@lovelock It's displayed in the top-right corner in the View Source page.

**Comment by lovelock** [comment]
@NGPixel Thanks for your reply and I've found it. 

However I think it would be more convenient if there is a button in the share pop up which is "Share with permanent URL" or something like that.

**Comment by NGPixel** [comment]
This will be addressed by aliases coming in v3.
