### ISSUE TITLE
Font Awesome 5 Icons are not displayed correctly on 2.1.107

### ISSUE THREAD

**Issue by mattbryce** [Requarks/wiki#1460]
**Describe the bug**
Font Awesome 5 Icons are not displayed correctly on 2.1.107. The div has a border radius which is obscuring the icons:

<div class="v-avatar v-list-item__avatar" style="height: 24px;min-width: 24px;width: 24px;"><i aria-hidden="true" class="v-icon notranslate fas fa-chalkboard theme--dark"></i></div>

.v-avatar {
    align-items: center;
     **border-radius: 50%;** 
    -js-display: inline-flex;
    display: inline-flex;
    justify-content: center;
    line-height: normal;
    position: relative;
    text-align: center;
    vertical-align: middle;
    overflow: hidden;
}

Disabling border radius resolves but some of the icons are still obscured. appears to also be a sizing issue.

**To Reproduce**
Displayed on Navigation bar

**Expected behavior**
The icons should not be cropped or obscured.

**Screenshots**
![image](https://user-images.githubusercontent.com/11202857/74155257-26a6b700-4c0c-11ea-90f6-45c23f717d79.png)

**Host Info (please complete the following information):**
 - OS: Windows_NT (win32) 10.0.14393 x64
 - Wiki.js version: 2.1.107
 - Database engine: mysql 8.0.11

**Additional context**
None

**Comment by NGPixel** [comment]
Already fixed by 9384ce14d53ce832fa8207abde85cfd6544bfa16

**Comment by mattbryce** [comment]
Still an issue in the admin area in 2.1.113:
![image](https://user-images.githubusercontent.com/11202857/74596903-670f9600-504d-11ea-8c9d-ffec794cb266.png)
