### ISSUE TITLE
ssh port - git stockage

### ISSUE THREAD

**Issue by valderaplets** [Requarks/wiki#1746]
The custom port ssh for git storage is forced to 22

**To Reproduce**
1. Go to Administration > storage > git
2. enter a port custom in "SSH PORT" example : 2345
3. Click on Force sync
4. in .git/config  : `sshCommand = ssh -i \"/root/.ssh/id_rsa\" -o StrictHostKeyChecking=no -p 22`

**Expected behavior**
`sshCommand = ssh -i \"/root/.ssh/id_rsa\" -o StrictHostKeyChecking=no -p 2345`

**Host Info :**
 - OS: debian buster 10.3
 - Wiki.js version: 2.3.51
 - Database engine: postgres 11

**Comment by Smankusors** [comment]
hmm... stockage?

**Comment by valderaplets** [comment]
My bad, french user. Issue modified.

**Comment by valderaplets** [comment]
Yeah or Storage (EN locales)
So, i've tested also with "ssdsqsdsqds" in the SSH PORT form.
Also 22 in `.git/config` :cry:

**Comment by Syphdias** [comment]
I can confirm this issue. removing the `-p 22` in `.git/config` from the `sshCommand` makes the `git fetch` work while being in the container (remember to `chown node. -R .` if done with root!) but it gets reset if triggered the "normal" way.

I'm also not quite sure why there is a separate setting for the port since it's included in the URI, e.g.
`ssh://git@example.com:5555/user/wikijs.git` – I think this worked in older versions without adding the custom port. I had to add the custom port when switching to docker beta tag a while ago I think.

**Comment by NGPixel** [comment]
Fixed by 2213ba2c816688b89bd76f5ac6d08ab8201ccbb1

**Comment by Syphdias** [comment]
I have reason to believe this didn't fix the issue.

![image](https://user-images.githubusercontent.com/16988672/80278028-6d785900-86f3-11ea-8fc9-4149110c2bb4.png)
```
❯ docker-compose images
Container    Repository        Tag        Image Id      Size 
-------------------------------------------------------------
wikidb      postgres        11-alpine   36ff18d21807   143 MB
wikijs      requarks/wiki   2.3         4477042c666e   379 MB
❯ docker inspect --format='{{.RepoDigests }}' 4477042c666e
[requarks/wiki@sha256:db6dd2e64af04cde109c9c4bd616a807ab6624dbd90a3fc3a45c8a7730c23b9b]
❯ docker-compose exec wikijs bash
bash-5.0$ cd /wiki/data/repo/
bash-5.0$ git config core.sshCommand
ssh -i "/wiki/data/secure/git-ssh.pem" -o StrictHostKeyChecking=no -p 22
❯ docker-compose exec wikidb bash
bash-5.0# psql wiki wikijs
psql (11.7)
Type "help" for help.

wiki=# \x on
Expanded display is on.
wiki=# select config from storage where "key" = 'git';
-[ RECORD 1 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
config | {"authType":"ssh","repoUrl":"ssh://git@example.com:12345/user/wikijs.git","branch":"master","sshPrivateKeyMode":"contents","sshPrivateKeyPath":"","sshPrivateKeyContent":"-----BEGIN OPENSSH PRIVATE KEY-----redacted-----END OPENSSH PRIVATE KEY-----","verifySSL":false,"basicUsername":"","basicPassword":"","defaultEmail":"git@example.com","defaultName":"wikijsgit","localRepoPath":"./data/repo","gitBinaryPath":"","sshPort":"12345"}
wiki=# 
```

I wouldn't even need the port option since it's included in the URI...

**Comment by valderaplets** [comment]
The same for me, without Docker

- SSH PORT = 1234

And after "APPLY" : 

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	sshCommand = ssh -i \"/root/.ssh/id_rsa\" -o StrictHostKeyChecking=no -p 22
```

After edit manually the files and click sur "APPLY" , same issue

**Comment by Syphdias** [comment]
Looks fixed now, thanks :) (see #1777)
