### ISSUE TITLE
Font Awesome 5 + Navigation has an issue

### ISSUE THREAD

**Issue by siddhartha-lal** [Requarks/wiki#1767]
**Describe the bug**
When using Font Awesome 5 for rendering the icons in the navigation area, the icons seems to be enclosed in a circular area.

**To Reproduce**
Going to the navigation area in the admin panel will reproduce the issue.

**Expected behavior**
I expected the icons to appear the way they are rendered on the Font Awesome website.
![Untitled](https://user-images.githubusercontent.com/56102539/80218937-d914e480-8667-11ea-9e89-1d88eedbf8f9.png)

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.2.51
 - Database engine: MySQL 5.7.29

**Additional context**
This issue was opened by another user, but was closed. I am using the latest version of Wiki.js, but the issue persists.

**Comment by NGPixel** [comment]
Fixed by 4b1e2c198815a4cf40987059c578dd268b963b9f.

Note that this only applies to the admin navigation page. The actual navbar was already displaying them correctly.

**Comment by siddhartha-lal** [comment]
I am sorry, but does this mean the fix will be released in the next version?

The current version of Wikijs is also not displaying them in the actual navbar correctly. Portion of the icon gets cut. I had to inject some CSS to make them appear correctly.

Thanks for your time.

**Comment by siddhartha-lal** [comment]
I upgraded to 2.2.72 and this issue still persists.
![Untitled3](https://user-images.githubusercontent.com/56102539/80280975-d7adef80-872d-11ea-8c84-f686a82d8e2f.png)
