### ISSUE TITLE
Input box input disappearing error

### ISSUE THREAD

**Issue by wlfcss** [Requarks/wiki#1805]
**Describe the bug**
- Input box input disappearing error

**To Reproduce**
1. Create a new papage
2. input page address down
3. input page name/description and more error
4. Input box input disappearing error （the screen gif Below）

**Expected behavior**
- The characters entered do not disappear.

**Screenshots**
![UUB2W](https://user-images.githubusercontent.com/12138285/80675934-443b3c80-8ae8-11ea-8c0a-898f3d530022.gif)

**Host Info (please complete the following information):**
 - local：OSX 10.15.3 - Chrome  81.0.4044.122
 - server-OS: [ubuntu18.04]
 - Wiki.js version: [latest 2.3.77]
 - Database engine: [postgres]
 - language: ZH-cn
 - Using Chinese Input Method：sougou-pinying

**Additional context**
This bug will also appear in the admin settings screen

**Comment by NGPixel** [comment]
This is fixed by #1783

**Comment by wlfcss** [comment]
This error still occurs in the global search box，When I use the chinese Input like a sougou-pinying
