### ISSUE TITLE
Sanitize HTML flag not respected in markdown editor

### ISSUE THREAD

**Issue by MarsWarrior** [Requarks/wiki#2431]
**Describe the bug**
As mentioned in #2415, the markdown editor does not respect the setting of the "Sanitize HTML" flag.

![image](https://user-images.githubusercontent.com/1220775/92999034-0e8a7380-f51e-11ea-8af0-c9def724fa6c.png)

**To Reproduce**
1. Disable the sanitize flag
2. In the markdown editor, create draw.io diagram with text containing line breaks
3. While editing, the diagram is NOT shown, but after save/close and displaying the resulting page, the diagram is shown.

**Expected behavior**
The flag is respected in both the editor and the page renderer.

**Screenshots**
While editing:
![image](https://user-images.githubusercontent.com/1220775/92999298-10edcd00-f520-11ea-8403-177e806ca820.png)

After save/close:
![image](https://user-images.githubusercontent.com/1220775/92999284-f0be0e00-f51f-11ea-9a39-c9d48021a877.png)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.132
 - Database engine: pg11

**Additional context**
Break.

**Comment by NGPixel** [comment]
Not a bug, the editor has a fixed configuration at the moment. Having the editor using the same pipeline as the server is planned for a future release.

**Comment by MarsWarrior** [comment]
Well, that’s an interesting won’t-fix-for-now as it is fixed in the current canary build 2.5.135 😄

**Comment by NGPixel** [comment]
It's fixed because the DOMPurify hook was added to the editor. Whatever you choose in Rendering is still not reflected in the preview window of the editor.
