### ISSUE TITLE
Long search results aren't scrollable

### ISSUE THREAD

**Issue by ravenzachary** [Requarks/wiki#942]
**Describe the bug**
When searching, a long list of search results is not scrollable past the first screen of results. In the case where there are 30 results, I can only see the first nine results on my desktop browser and the first six on my phone.

**To Reproduce**
1. Search for a common topic or word from the home page of your wiki.
2. Search results are displayed. They are not scrollable to see all the results.

**Expected behavior**
The list of search results would be scrollable or paginated.

**Screenshots**
None provided, as it is hard to show using a static screenshot.

**Host Info (please complete the following information):**
I am running these tests on Mac OS (Safari and Chrome) and iOS (Mobile Safari)

**Additional context**
n/a

**Comment by NGPixel** [comment]
Fixed by 9c40975aebd54fa973b1b019e9c85b9d93ff6ef2

**Comment by ravenzachary** [comment]
This bug is still present for me in 2.3.77 for both the latest Safari and Chrome versions on Mac ans as well as the latest Mobile Safari on iOS. I have not tested on a PC (none with me currently).

**Comment by ravenzachary** [comment]
This bug is still present for me in 2.4.105.

**Comment by Smankusors** [comment]
there's PR that supposed to fix this #2232
