### ISSUE TITLE
search 

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#968]
**Question**
Search functionality is not working.

**Host Info (please complete the following information):**
OS: Ubuntu 18.04
Wiki.js version: [e.g. 2.0.0-beta.115]
Database engine: mysql Ver 8.0.17

The error is displayed below.
![image](https://user-images.githubusercontent.com/46513658/63268645-45a63b00-c2b2-11e9-9d76-acee7bfed591.png)

**Comment by devp01** [comment]
I was just trying to search a page. Tried home page and the error message is as above.  I am using mysql Ver 8.0.17.

**Comment by JBleijenberg** [comment]
I'm experiencing the same, but with ElasticSearch as backend. The nodes aren't being indexed, even with manual indexing from the admin

**Comment by NGPixel** [comment]
Please update to the latest version of wiki.js first. If the bug still occurs, we'll troubleshoot.

**Comment by RickCogley** [comment]
Not sure if it is related but, I cannot search either Japanese or English in 2.0.0-beta.268, installed via docker compose.

**Comment by joseantonnio** [comment]
Not working here either!

**To Reproduce**
Type anything in search input and the error "An unexpected error occured" shows up.

**Expected behavior**
Return  search results OR message "An unexpected error occured" should be "An unexpected error occurred".

**Screenshots**
![image](https://user-images.githubusercontent.com/9931324/64049392-15c92400-cb4b-11e9-907e-33bdb6240e53.png)

**Host Info (please complete the following information):**
OS: Ubuntu 18.04.2 LTS
Wiki.js version: 2.0.0-beta.275
Database engine: MySQL 5.7.26

**Extra Information**
GraphQL request response:
```json
[{"errors":[{"message":"select `id`, `title`, `description`, `path`, `localeCode` as `locale` from `pages` where (`isPublished` = true and (title LIKE '%'Mark'%' COLLATE utf8_general_ci or description LIKE '%'Mark'%' COLLATE utf8_general_ci)) limit 100 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Mark'%' COLLATE utf8_general_ci or description LIKE '%'Mark'%' COLLATE utf8_gene' at line 1","locations":[{"line":3,"column":5}],"path":["pages","search"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"code":"ER_PARSE_ERROR","errno":1064,"sqlState":"42000","sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Mark'%' COLLATE utf8_general_ci or description LIKE '%'Mark'%' COLLATE utf8_gene' at line 1"}}}],"data":{"pages":null}}]
```

**Comment by tverdohleb** [comment]
@NGPixel 
Faced the same issue. This is how knex escapes strings.
Raw queries like [this one](https://github.com/Requarks/wiki/blob/master/server/modules/search/db/engine.js#L42) will cause such behavior because knex wraps strings with quotes when binding string values. You might consider replacing it with something like this:
```
builder.whereRaw(`title LIKE ? COLLATE utf8_general_ci`, [`%${q}%`]) 
```

**Comment by joseantonnio** [comment]
Updated to 2.0.0-beta.303 and still occuring.

**Comment by joseantonnio** [comment]
Today I've configured CloudSearch and this bug was gone! Looks like @tverdohleb is really right. Problem is related to knex query and local database.

**Comment by mattbryce** [comment]
I have the same issue on 2.0.0-beta.303

Host Info:
OS: Windows_NT (win32) 10.0.14393 x64
Wiki.js version: 2.0.0-beta.303
Node.js: 10.16.3
Database engine: MySQL 8.0.11

**Comment by mattbryce** [comment]
Still an issue on **2.0.0-rc.1**

Host Info:
OS: Windows_NT (win32) 10.0.14393 x64
Wiki.js version: 2.0.0-rc.1
Node.js: 10.16.3
Database engine: MySQL 8.0.11

Issue appears linked to #842 #909

**Comment by centell** [comment]
I have the same issue on `wiki.js 2.0.0-rc.1`

Host info:
```
OS: Ubuntu 18.04.3 LTS
Wiki.js: 2.0.0-rc.1
Node.js: v12.13.0
Database engine: mysql  Ver 15.1 Distrib 10.3.18-MariaDB, for debian-linux-gnu (x86_64) 
```

**Comment by NGPixel** [comment]
Fixed by d69dde1df5c2db74c10fe86ead50a63528c4487d

**Comment by anibal-aguila** [comment]
I have the same issue...
OS: Centos 7/8 
Wiki.js: 2.0.0-rc.17
Doker:
 image: requarks/wiki:dev
 image: postgres:12.0-alpine

![image](https://user-images.githubusercontent.com/49025536/68530961-77f19280-030d-11ea-9ee8-85e2210f5d05.png)

**Comment by s1rauch** [comment]
I still have the same issue too
OS: Debian 10 Buster
Wiki.js: 2.2.51
Node.js: 10.15.2
PostgreSQL: 11.7
@anibal-aguila i think your version is too old the bugfix comes with the version https://github.com/Requarks/wiki/releases/tag/2.0.1
